# Generated by Django 6.0.4 on 2026-05-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Введите название своей страны",
                max_length=35,
                null=True,
                verbose_name="Страна",
            ),
        ),
    ]
