# Generated by Django 6.0.2 on 2026-04-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=250, verbose_name="заголовок"),
        ),
    ]
