# Generated by Django 6.0.2 on 2026-05-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title"],
                "verbose_name": "Блог",
                "verbose_name_plural": "Блог",
            },
        ),
    ]
