# Generated by Django 6.0.4 on 2026-05-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
